### ISSUE TITLE
DRAFT Kororaa Feature: total rupture rate for IFM Analysis

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/kororaa#299]
provide sum of rupture rates for all ruptures that pass filter in IFM Analysis. May require update to solvis-api

**Comment by chrisbc** [comment]
@chrisdicaprio what is the math needed here? should be doable in API pretty simply as we have our geopandas right there

**Comment by chrisdicaprio** [comment]
@chrisbc if the values are in rate (i.e., events per year), which I believe they are, you can simply sum them.
