### ISSUE TITLE
Kororaa Feature: Minor top level UI tweaks for next release

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/kororaa#376]
To improve UX and cater for latest feature changes, we'd want to 

 - [x] drop the "Coming Features" tile from home page
 - [x] add a tile for "Rupture Map" to home page
 - [x] Remove the "Ruptures and Rates view" tile from "Coming Features" page
 - [ ] Improve the main menu display of currently selected menu item.
     a new button style to replace the underlined text style?

**Comment by chrisdicaprio** [comment]
- [ ] Change name in menu from "Rupture Map" to "Ruptures"
 - [ ] Change text in Previews from "Things we expect to include over the coming months." to "Features we expect to add in the future."
