### ISSUE TITLE
Kororaa Fix: MFD plot bounds

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/kororaa#377]
In Rupture map view 

The maximum M for  MFD plot needs to be larger to accommodate ruptures in the M=9.6 bin ....

![image](https://github.com/GNS-Science/kororaa/assets/8263318/70a4a229-f3d9-4871-afd4-cbf8f551ba7b)

in this plot there should be an incremental bar for the 9.6 ruptures that lines up with the cumulative line...

## to reproduce 
 - System:  Hikurangi
 - Location: Whanganui
 - radius: 100
 - Min Mag: 8.0
 - sort by: Mag descending

**Comment by chrisdicaprio** [comment]
Additional rats and mice:
- rate and cumulative rate in tooltip should read "XXX /yr"
- y-axis label should read "Rate (1/yr)"
- label on colorbar should read "Participation Rate (1/yr)"
